appname = academica_core_service
httpport = 8080
runmode = ${ACADEMICA_CORE_SERVICE_RUN_MODE||prod}
autorender = false
copyrequestbody = true

parameterStore = ${PARAMETER_STORE}

ORuser=${ACADEMICA_CORE_SERVICE_ORUSER}
ORpass=${ACADEMICA_CORE_SERVICE_ORPASS}
ORhost=${ACADEMICA_CORE_SERVICE_ORHOST}
ORport=${ACADEMICA_CORE_SERVICE_ORPORT}
ORservice=${ACADEMICA_CORE_SERVICE_ORSERVICE}
